Use an official Node runtime as a parent image

FROM node:20-slim

Set the working directory in the container to /usr/src/app

WORKDIR /usr/src/app

Copy package.json and package-lock.json to the working directory

We do this first to leverage Docker's caching, only re-running install if these files change

COPY package*.json ./

Install app dependencies

RUN npm install

Copy the rest of the application source code

COPY . .

The application runs on port 3000, which must be exposed

EXPOSE 3000

Define the command to run the app

CMD [ "npm", "start" ]